# This is a basic workflow to help you get started with Actions

name: learn-github-actions

# Controls when the action will run. 
# Triggers the workflow on push or pull request events but only for the main branch
on: [push] 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "check-bats-version"
  check-bats-version:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        # Steps up node
      - uses: actions/setup-node@v2
        # Installs bat
      - run: npm install testcafe
        # Checks the version of bats installed
      - run: testcafe -version
        # Checks the version of node installed
      - run: node -v
